#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt',
    :git => 'https://github.com/opscode-cookbooks/apt.git'
cookbook 'nodejs',
   :git => 'https://github.com/mdxp/nodejs-cookbook.git'
cookbook 'git',
   :git => 'https://github.com/opscode-cookbooks/git.git'
cookbook 'vim'